CREATE TABLE `tbl_languages` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `Java` INT NULL DEFAULT 0,
  `Python` INT NULL DEFAULT 0,
  `C` INT NULL DEFAULT 0,
  `Ruby` INT NULL DEFAULT 0,
  `Hadoop` INT NULL DEFAULT 0,
  `CSS` INT NULL DEFAULT 0,
  `PHP` INT NULL DEFAULT 0,
  `Haskell` INT NULL DEFAULT 0,
  `Mysql` INT NULL DEFAULT 0,
  `Mathematica` INT NULL DEFAULT 0,
  `Matlab` INT NULL DEFAULT 0,
  `Solid_Works` INT NULL DEFAULT 0, 
  `Cuda` INT NULL DEFAULT 0,
  `Assembly` INT NULL DEFAULT 0,
  PRIMARY KEY(`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;